const time = new Date();

const date = time.getDate();

const month = time.getMonth();

const year= time.getFullYear();

export const DummyChats = [
    {
      name: "John Doe",
      number: "1234567890",
      about: "Lorem ipsum dolor sit amet",
      key: "1625489378000",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?fruit",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Jane Smith",
      number: "9876543210",
      about: "Consectetur adipiscing elit",
      key: "1625489378001",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?cricket",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Alice Johnson",
      number: "5555555555",
      about: "Sed do eiusmod tempor incididunt",
      key: "1625489378002",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?ball",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Bob Anderson",
      number: "9999999999",
      about: "Ut labore et dolore magna aliqua",
      key: "1625489378003",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?bat",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Emma Davis",
      number: "1111111111",
      about: "Quis nostrud exercitation ullamco",
      key: "1625489378004",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?code",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Michael Wilson",
      number: "7777777777",
      about: "Duis aute irure dolor in reprehenderit",
      key: "1625489378005",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?laptop",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Olivia Brown",
      number: "4444444444",
      about: "Excepteur sint occaecat cupidatat",
      key: "1625489378006",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?blue",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "David Taylor",
      number: "6666666666",
      about: "Sunt in culpa qui officia deserunt",
      key: "1625489378007",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?snake",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Sophia Miller",
      number: "2222222222",
      about: "Mollit anim id est laborum",
      key: "1625489378008",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?melon",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "James Wilson",
      number: "8888888888",
      about: "Sed ut perspiciatis unde omnis",
      key: "1625489378009",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?mango",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Ava Anderson",
      number: "3333333333",
      about: "Nemo enim ipsam voluptatem",
      key: "1625489378010",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?orange",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "William Davis",
      number: "9999999999",
      about: "Tempor incididunt ut labore et dolore",
      key: "1625489378011",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?grapes",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Mia Johnson",
      number: "1111111111",
      about: "Sed ut perspiciatis unde omnis",
      key: "1625489378012",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?banana",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Benjamin Thompson",
      number: "7777777777",
      about: "Nisi ut aliquid ex ea commodi",
      key: "1625489378013",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?strawberry",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Harper Martinez",
      number: "4444444444",
      about: "Quis autem vel eum iure reprehenderit",
      key: "1625489378014",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?shoes",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Elijah Wilson",
      number: "6666666666",
      about: "Voluptate velit esse cillum dolore",
      key: "1625489378015",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?socks",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Charlotte Brown",
      number: "2222222222",
      about: "Excepteur sint occaecat cupidatat",
      key: "1625489378016",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?bag",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Daniel Smith",
      number: "8888888888",
      about: "Sed do eiusmod tempor incididunt",
      key: "1625489378017",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?mouth",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Sophia Taylor",
      number: "3333333333",
      about: "Ut enim ad minim veniam",
      key: "1625489378018",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?face",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    },
    {
      name: "Jacob Anderson",
      number: "9999999999",
      about: "Quis autem vel eum iure reprehenderit",
      key: "1625489378019",
      date,
      month,
      year,
      photo: "https://source.unsplash.com/random/900×700/?cool",
      selected: false,
      pinned: false,
      muted: false,
      readed: false,
    }
  ];
  